"""empty message

Revision ID: 2e3d62f3c2ed
Revises: 35daf1dd614c
Create Date: 2025-12-16 22:49:54.068435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3d62f3c2ed'
down_revision = '35daf1dd614c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('superhero_name', sa.String(length=120), nullable=False),
    sa.Column('powers', sa.Text(), nullable=True),
    sa.Column('weakness', sa.Text(), nullable=True),
    sa.Column('origins', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
