"""add pdf_file to comics

Revision ID: 35daf1dd614c
Revises: d0427b7c2adb
Create Date: 2025-12-14 16:23:16.241621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35daf1dd614c'
down_revision = 'd0427b7c2adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.drop_column('pdf_file')

    # ### end Alembic commands ###
