"""empty message

Revision ID: 58d083bf9370
Revises: 992c52324c86
Create Date: 2025-12-17 04:49:23.944475

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '58d083bf9370'
down_revision = '992c52324c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
