"""add characters table

Revision ID: 992c52324c86
Revises: 2e3d62f3c2ed
Create Date: 2025-12-17 04:06:40.764441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992c52324c86'
down_revision = '2e3d62f3c2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('superhero_name', sa.String(length=120), nullable=False),
    sa.Column('powers', sa.Text(), nullable=True),
    sa.Column('weakness', sa.Text(), nullable=True),
    sa.Column('origins', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
